### ISSUE TITLE
Unable To Use Latest jQuery

### ISSUE THREAD

**Issue by 9mido** [bmihelac/django-cookie-consent#16]
I am using the test_page.html as my cookie bar setup. But cannot switch out https://github.com/bmihelac/django-cookie-consent/blob/master/tests/core/templates/test_page.html#L58 with the latest jQuery:

`<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
`

The accept and decline links for the cookie bar on line 85 does not work. 

It is kind of undesirable to use 2 versions of jQuery 3.3.1 and the newest in my code which is a quick way around this when you should just be able to use the latest. Otherwise the jQuery that this app uses needs to be modernized. 

Maybe there is a way to completely avoid jQuery and use JavaScript only?

**Comment by bmihelac** [comment]
@9mido thanks for report, this should be resolved with https://github.com/bmihelac/django-cookie-consent/pull/20

please reopen if it is not

**Comment by 9mido** [comment]
@bmihelac Awesome! I will have to test it and check it out thanks!
