### ISSUE TITLE
Python 2 support.

### ISSUE THREAD

**Issue by Jasper-Koops** [bmihelac/django-cookie-consent#17]
Let me begin by acknowledging that python 2 is EOL and that the best course of action may be to simple update the README and remove all mentions of python 2.  

Currently the README does indicate that the app supports python 2, but one of its dependencies [django-appconf](https://github.com/django-compressor/django-appconf) [no longer does as of version 1.0.4 ](https://github.com/django-compressor/django-appconf/issues/71) 

[It seems they dropped support in a point release](https://github.com/django-compressor/django-appconf/commit/8dcd89d5d386d4b3f09ca85d549a706bae12d8e3#r38173892) and as such it may not have been clear to the authors of django-cookie-consent that the 1.0.4 release of django-appconf actually included a 'breaking change'.  (Though again, I acknowledge that python 2 is no longer supported in general, and as such it may be somewhat disingenuous of me to treat it as a 'breaking change').

I ran into this issue when trying to install `django-cookie-consent` in a `python2/django1.11` project at work (whilst simultaneously lobbying for a python 3 upgrade) which will now throw the following `ImportError: No module named importlib` error:

`File "***/venv/local/lib/python2.7/site-packages/cookie_consent/conf.py", line 9, in <module>
    class CookieConsentConf(AppConf):
  File "***/venv/local/lib/python2.7/site-packages/appconf/base.py", line 53, in __new__
    new_class.add_to_class('_meta', AppConfOptions(meta, prefix))
  File "***/venv/local/lib/python2.7/site-packages/appconf/base.py", line 12, in __init__
    self.holder = import_attribute(self.holder_path)
  File "***/venv/local/lib/python2.7/site-packages/appconf/utils.py", line 5, in import_attribute
    from django.utils.importlib import import_module
ImportError: No module named importlib
`

Suggested fixes:

1. Dropping the mention of python 2 support, its EOL after all.
2. If the decision is made to keep python 2 support - settings the requirement  of `django-appconf`  to version <=1.0.3

Thanks for your hard work!

**Comment by bmihelac** [comment]
good catch @Jasper-Koops . 
Would you like to make PR to set the requirement of django-appconf to version <=1.0.3?

**Comment by bmihelac** [comment]
fix in 0.2.1
