### ISSUE TITLE
Mistype in doc

### ISSUE THREAD

**Issue by JurajKavkaAdaptiware** [bmihelac/django-cookie-consent#2]
In docs is little typo `coookie_consent` - tripple `o`

[https://django-cookie-consent.readthedocs.org/en/latest/configuration.html](https://django-cookie-consent.readthedocs.org/en/latest/configuration.html)

**Comment by bmihelac** [comment]
Thanks for noticing @JurajKavka . Would you like to submit a pull request?

**Comment by JurajKavka** [comment]
hi. yes i have prepared another fork with django 1.8 support (please check it and give me the feedback - i removed south. it was probably bad idea :/ ). but i need some time because i'm very busy these days... im not familiar with documentation. i need to learn how to fix and build docs...

**Comment by sergei-maertens** [comment]
Seems to have been fixed in caecc6c76b3703013a37f3366f080ef0752d5ec6
