### ISSUE TITLE
Cookie Bar Choosing Decline Not Disappearing Right Away

### ISSUE THREAD

**Issue by 9mido** [bmihelac/django-cookie-consent#21]
Mentioned in https://github.com/bmihelac/django-cookie-consent/pull/20

**Comment by MrCordeiro** [comment]
Oops!

**Comment by MrCordeiro** [comment]
There!
https://github.com/bmihelac/django-cookie-consent/pull/22

**Comment by bmihelac** [comment]
@9mido thanks for reporting and @MrCordeiro for fix. In 0.2.7
