### ISSUE TITLE
Spam Protection

### ISSUE THREAD

**Issue by 9mido** [bmihelac/django-cookie-consent#28]
https://github.com/bmihelac/django-cookie-consent/blob/master/cookie_consent/templates/cookie_consent/_cookie_group.html

Problem: 

The database can get really spammed / filled up with log items with people / bots spam clicking accept or decline more than once on the cookie group page. 

Ideas: 

1. Delete the log database entries with a cron job with a manage.py command or perhaps a postgres mechanism of some kind? 

2. Create a setting to stop logging all together as an option. This would be a great feature to have in my opinion in addition to some sort of spam click protection on the cookie group page. 

3. Create a setting/JavaScript code for only accepting or declining every X number of minutes? Similar to Reddit and Stackoverflow. https://i.stack.imgur.com/4J3jr.png

4. JavaScript disable/hide the accept or decline buttons after clicking the first time for that particular cookie. You are only able to submit the form once then the button gets disabled/hidden afterwards for that page load unless the user refreshes. Unless you do not use a for loop and generate each cookie group separately.

5. If do deciding to keep logging enabled, change the accept/decline views to prevent clicking so many times and filling up the database. 

https://stackoverflow.com/questions/31591356/allow-form-submission-only-once-a-day-django

**Comment by MrCordeiro** [comment]
I think having conditional logging makes sense. Here's an idea how to do it.

Defining a conditional model will run migrations everytime you switch the condition on or off. That may leave users scratching their heads.

A better option would be to move the logging model into its own app and append it to `INSTALLED_APPS` conditionally.

Something like this:

```
#settings.py 
ENABLE_LOGGING = True 

INSTALLED_APPS = [...] 

if CONSUMER_REGISTRATION:     INSTALLED_APPS.append('cookie_logging') # Models will be loaded.
```

There's nothing wrong with creating an app which just contains a model. The table will only be created of migrations are run when the setting is true, but it won't delete the it if is changed to false.

**Comment by 9mido** [comment]
Thank you @MrCordeiro the PR worked perfectly! So awesome!

@bmihelac can you please upload this to PyPi? I will close this when docs for this new setting and PyPi gets released.

**Comment by sergei-maertens** [comment]
This seems to be on PyPI, so I'm closing this issue to reduce noise in the repo. Feel free to reopen if I'm mistaken!
