### ISSUE TITLE
Setting COOKIE_CONSENT_LOG_ENABLED to False does stop log events from writing to Db

### ISSUE THREAD

**Issue by Dandada1993** [bmihelac/django-cookie-consent#32]
Set COOKIE_CONSENT_LOG_ENABLED = False as suggested in the Docs but accepts and declines are still being logged.

**Comment by 9mido** [comment]
@Dandada1993 there is no updated PyPi yet with the new log feature.

In your requirements.txt make sure you include this:
-e git+git://github.com/bmihelac/django-cookie-consent#egg=django-cookie-consent

That way, you should be able to use the new log feature.

**Comment by Dandada1993** [comment]
Thanks for the reply.
  
  
   
  
  
   I monkey patched the accept_cookies and decline_cookie methods to make the call to LogItem contingent on COOKIE_CONSENT_LOG_ENABLED.
  
  
   
  
  
   Regards,
  
  
   
    On September 6, 2020 10:25 PM 9mido <notifications@github.com> wrote:
   
   
    
   
   
    
   
   
   @Dandada1993 there is no updated PyPi yet with the new log feature.
   In your requirements.txt make sure you include this:-e git+git://github.com/bmihelac/django-cookie-consent#egg=django-cookie-consent
   That way, you should be able to use the new log feature.

**Comment by Dandada1993** [comment]
I used this SO answer https://stackoverflow.com/questions/6720858/how-to-monkey-patch-django

**Comment by 9mido** [comment]
@Dandada1993 Thanks. Just to confirm, did you use the github version of the package and not the PyPi one when you found this problem?

**Comment by Dandada1993** [comment]
I used the PyPi one. I just checked and the Git Hub code has the check for COOKIE_CONSENT_LOG_ENABLED.

In terms of how I fixed it. I added the following methods (copied from your util.py) to a utils module I have and added the "if settings.COOKIE_CONSENT_LOG_ENABLED:" condition.

def accept_cookies(request, response, varname=None):
    """
    This method is used to monkey path cookie_consent.util.accept_cookies
    as it doesn't honour the COOKIE_CONSENT_LOG_ENABLED flag.

    Accept cookies in Cookie Group specified by ``varname``.
    """
    cookie_dic = get_cookie_dict_from_request(request)
    for cookie_group in get_cookie_groups(varname):
        cookie_dic[cookie_group.varname] = cookie_group.get_version()
        if settings.COOKIE_CONSENT_LOG_ENABLED:
            LogItem.objects.create(action=ACTION_ACCEPTED,
                                cookiegroup=cookie_group,
                                version=cookie_group.get_version())
    set_cookie_dict_to_response(response, cookie_dic)


def decline_cookies(request, response, varname=None):
    """
    This method is used to monkey path cookie_consent.util.decline_cookies
    as it doesn't honour the COOKIE_CONSENT_LOG_ENABLED flag.

    Decline and delete cookies in CookieGroup specified by ``varname``.
    """
    cookie_dic = get_cookie_dict_from_request(request)
    for cookie_group in get_cookie_groups(varname):
        cookie_dic[cookie_group.varname] = settings.COOKIE_CONSENT_DECLINE
        delete_cookies(response, cookie_group)
        if settings.COOKIE_CONSENT_LOG_ENABLED:
            LogItem.objects.create(action=ACTION_DECLINED,
                                cookiegroup=cookie_group,
                                version=cookie_group.get_version())
    set_cookie_dict_to_response(response, cookie_dic)

In apps.py I overwrote the ready method of AppConfig with the following:

def ready(self):
        """
        Monkey patching 
            cookie_consent.util.accept_cookies
            cookie_consent.util.decline_cookies
        Patching with:
            users.utils.accept_cookies
            users.utils.decline_cookies
        Reason:
        
        Cookie Consent's accept_cookies and decline_cookies ignore the COOKIE_CONSENT_LOG_ENABLED
        flag. The methods from users.utils honour COOKIE_CONSENT_LOG_ENABLED.
        """
        from cookie_consent import util
        from users.utils import (
            accept_cookies,
            decline_cookies
        )
        util.accept_cookies = accept_cookies
        util.decline_cookies = decline_cookies

**Comment by Dandada1993** [comment]
I used the PyPi one. I just checked and the Git Hub code has the check for COOKIE_CONSENT_LOG_ENABLED.

In terms of how I fixed it. I added the following methods (copied from your util.py) to a utils module I have and added the "if settings.COOKIE_CONSENT_LOG_ENABLED:" condition.

`def accept_cookies(request, response, varname=None):
	"""
	This method is used to monkey path cookie_consent.util.accept_cookies
	as it doesn't honour the COOKIE_CONSENT_LOG_ENABLED flag.

	Accept cookies in Cookie Group specified by ``varname``.
	"""
	cookie_dic = get_cookie_dict_from_request(request)
	for cookie_group in get_cookie_groups(varname):
		cookie_dic[cookie_group.varname] = cookie_group.get_version()
		if settings.COOKIE_CONSENT_LOG_ENABLED:
			LogItem.objects.create(action=ACTION_ACCEPTED,
								cookiegroup=cookie_group,
								version=cookie_group.get_version())
	set_cookie_dict_to_response(response, cookie_dic)`

`def decline_cookies(request, response, varname=None):
	"""
	This method is used to monkey path cookie_consent.util.decline_cookies
	as it doesn't honour the COOKIE_CONSENT_LOG_ENABLED flag.

	Decline and delete cookies in CookieGroup specified by ``varname``.
	"""
	cookie_dic = get_cookie_dict_from_request(request)
	for cookie_group in get_cookie_groups(varname):
		cookie_dic[cookie_group.varname] = settings.COOKIE_CONSENT_DECLINE
		delete_cookies(response, cookie_group)
		if settings.COOKIE_CONSENT_LOG_ENABLED:
			LogItem.objects.create(action=ACTION_DECLINED,
								cookiegroup=cookie_group,
								version=cookie_group.get_version())
	set_cookie_dict_to_response(response, cookie_dic)

In apps.py I overwrote the ready method of AppConfig with the following:

`def ready(self):
	"""
	Monkey patching
	cookie_consent.util.accept_cookies
	cookie_consent.util.decline_cookies
	
	Patching with:
	users.utils.accept_cookies
	users.utils.decline_cookies
	
	Reason:

	Cookie Consent's accept_cookies and decline_cookies ignore the COOKIE_CONSENT_LOG_ENABLED
	flag. The methods from users.utils honour COOKIE_CONSENT_LOG_ENABLED.
	"""
	
	from cookie_consent import util
	from users.utils import (
		accept_cookies,
		decline_cookies
	)
	util.accept_cookies = accept_cookies
	util.decline_cookies = decline_cookies`

**Comment by MrCordeiro** [comment]
@bmihelac, did something happen? 
Pypi doesn't have the latest package version for 2 months by now.

**Comment by sergei-maertens** [comment]
Since the last activity here, there have been PyPI releases so I think this is resolved. Feel free to reopen if I'm mistaken!
