### ISSUE TITLE
Fails in Django 2.0

### ISSUE THREAD

**Issue by manuganji** [bmihelac/django-cookie-consent#4]
> File "./../cookie_consent/cache.py", line 4, in <module>
> from django.core.cache import get_cache
> ImportError: cannot import name 'get_cache'

**Comment by slow999** [comment]
Fails in Django 1.11 as well.

**Comment by bmihelac** [comment]
PR welcomed :)

**Comment by philmaweb** [comment]
How about @JonHerr or @haricot to merge the Forks back into master?

**Comment by JonHerr** [comment]
I added a pull request for my edits. it supports 1.9 to current there is also a travis ci if you wish to add that to your github

**Comment by bmihelac** [comment]
fixed in fba13422624707a40c9cbaedee61972e2afaf66e
