### ISSUE TITLE
How do I add a google analytics

### ISSUE THREAD

**Issue by LanceMeister** [bmihelac/django-cookie-consent#40]
I looked at the test app but I was unable to see how to include a google analytics tag. is it supposed to placed in the field called "Path" from the admin? or in the script. google analytics produces a tag for every account. how do I implement this tag so it is accepted or declined by Django cookie consent?

**Comment by sergei-maertens** [comment]
I'm going to close this as I think the answer from 9mido is sufficient, and this particular question is out of scope of this library.
