### ISSUE TITLE
Support for multiple languages?

### ISSUE THREAD

**Issue by vocationeers** [bmihelac/django-cookie-consent#8]
Would it be possible to add support for multiple languages?

This module seems to be the closest to a throughout cookie manager for Django that is compatible with EU laws. However, the actual cookie descriptions would need to be translated as well which is not possible at this time. Maybe it would be possible to create an interface to Parler or something similar

**Comment by bmihelac** [comment]
@vocationeers I have successfully used it without any change with django-modeltranslation which allows translating 3rd party apps

**Comment by vocationeers** [comment]
Thanks a million for your fast response. Totally solved my request.

For anyone interested this would be the piece of code that needs to be added to translation.py:

`from modeltranslation.translator import translator, TranslationOptions
from cookie_consent.models import Cookie, CookieGroup

class CookieTranslationOptions(TranslationOptions):
    fields = ('description',)

class CookieGroupTranslationOptions(TranslationOptions):
    fields = ('name', 'description',)

translator.register(Cookie, CookieTranslationOptions)
translator.register(CookieGroup, CookieGroupTranslationOptions)`
